version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: contenedor_entrevista_solati_web
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: entrevista
      PG_USER: root
      PG_PASSWORD: 1234

  db:
    image: postgres:latest
    container_name: contenedor_entrevista_solati_bd_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: entrevista
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    command: ["postgres", "-c", "listen_addresses=0.0.0.0", "-c", "fsync=off"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    